[package]
name = "CoPilotS"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
cpal = "0.15.3"
tonic = { version = "0.5", features = ["prost"] }
prost = "0.8"
prost-types = "0.8"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
tonic-build = "0.5"
